import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";

import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { sendPaymentReminderEmail } from "@/lib/email";
import { decrypt } from "@/lib/encryption";

function formatCurrency(value: unknown) {
  return `₹${Number(value).toLocaleString("en-IN")}`;
}

function formatDate(value: Date) {
  return value.toLocaleDateString("en-IN");
}

export async function GET(request: Request) {
  try {
    const session = await getServerSession(authOptions);

    if (!session) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const search = searchParams.get("search") || "";

    const reminders = await prisma.reminder.findMany({
      where: {
        userId: session.user.id,
        OR: search
          ? [
            {
              sentTo: {
                contains: search,
                mode: "insensitive",
              },
            },
            {
              subject: {
                contains: search,
                mode: "insensitive",
              },
            },
            {
              customer: {
                name: {
                  contains: search,
                  mode: "insensitive",
                },
              },
            },
            {
              customer: {
                email: {
                  contains: search,
                  mode: "insensitive",
                },
              },
            },
            {
              invoice: {
                invoiceNumber: {
                  contains: search,
                  mode: "insensitive",
                },
              },
            },
          ]
          : undefined,
      },
      include: {
        customer: true,
        invoice: true,
      },
      orderBy: {
        createdAt: "desc",
      },
    });

    return NextResponse.json(reminders);
  } catch (error) {
    console.error("REMINDERS_GET_ERROR", error);

    return NextResponse.json(
      { message: "Something went wrong" },
      { status: 500 }
    );
  }
}

export async function POST(request: Request) {
  try {
    const session = await getServerSession(authOptions);

    if (!session) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const { invoiceId } = body;

    if (!invoiceId) {
      return NextResponse.json(
        { message: "Invoice ID is required" },
        { status: 400 }
      );
    }

    const invoice = await prisma.invoice.findFirst({
      where: {
        id: invoiceId,
        userId: session.user.id,
      },
      include: {
        customer: true,
        user: true,
      },
    });

    if (!invoice) {
      return NextResponse.json(
        { message: "Invoice not found" },
        { status: 404 }
      );
    }

    if (invoice.status === "PAID") {
      return NextResponse.json(
        { message: "Cannot send reminder for a paid invoice" },
        { status: 400 }
      );
    }

    if (!invoice.customer.email) {
      return NextResponse.json(
        { message: "Customer email is missing" },
        { status: 400 }
      );
    }

    const subject = `Payment Reminder for Invoice ${invoice.invoiceNumber}`;

    const message = `Dear ${invoice.customer.name},

This is a payment reminder for invoice ${invoice.invoiceNumber}.

Amount Due: ${formatCurrency(invoice.balanceAmount)}
Due Date: ${formatDate(invoice.dueDate)}

Kindly complete the payment at the earliest.

Regards,
${invoice.user.businessName || invoice.user.name || "Your Business"}`;

    // HTML template is now generated by the email service

    const reminder = await prisma.reminder.create({
      data: {
        userId: session.user.id,
        customerId: invoice.customerId,
        invoiceId: invoice.id,
        reminderType:
          invoice.status === "OVERDUE"
            ? "OVERDUE"
            : "BEFORE_DUE_DATE",
        status: "PENDING",
        subject,
        message,
        sentTo: invoice.customer.email,
      },
    });

    try {
      const emailResponse = await sendPaymentReminderEmail({
        to: invoice.customer.email,
        customerName: invoice.customer.name,
        invoiceNumber: invoice.invoiceNumber,
        amountDue: formatCurrency(invoice.balanceAmount),
        dueDate: formatDate(invoice.dueDate),
        businessName: invoice.user.businessName || invoice.user.name || "Your Business",
        invoiceStatus: invoice.status,
        isOverdue: invoice.status === "OVERDUE",
        reminderMessage: message,
        senderEmail: invoice.user.email,
        senderPass: invoice.user.emailPass ? decrypt(invoice.user.emailPass) : undefined,
      });

      if (!emailResponse.success) {
        const errorMsg = (emailResponse.error as any)?.code === "EAUTH"
          ? "Gmail authentication failed. Please verify that your Gmail App Password in settings is correct."
          : "Failed to send email via SMTP server.";
        const customError = new Error(errorMsg) as any;
        customError.status = 400;
        throw customError;
      }

      const updatedReminder = await prisma.reminder.update({
        where: {
          id: reminder.id,
        },
        data: {
          status: "SENT",
          resendEmailId: emailResponse.messageId as string,
          sentAt: new Date(),
        },
      });

      return NextResponse.json(
        {
          message: "Reminder email sent successfully",
          reminder: updatedReminder,
        },
        { status: 201 }
      );
    } catch (emailError: any) {
      console.error("RESEND_EMAIL_ERROR", emailError);

      const failedReminder = await prisma.reminder.update({
        where: {
          id: reminder.id,
        },
        data: {
          status: "FAILED",
        },
      });

      return NextResponse.json(
        {
          message: emailError.message || "Reminder saved but email sending failed",
          reminder: failedReminder,
        },
        { status: emailError.status || 500 }
      );
    }
  } catch (error) {
    console.error("REMINDERS_POST_ERROR", error);

    return NextResponse.json(
      { message: "Something went wrong" },
      { status: 500 }
    );
  }
}