// import { NextResponse } from "next/server";

// import { prisma } from "@/lib/prisma";
// import { sendPaymentReminderEmail } from "@/lib/email";

// function startOfDay(date: Date) {
//   const result = new Date(date);
//   result.setHours(0, 0, 0, 0);
//   return result;
// }

// function endOfDay(date: Date) {
//   const result = new Date(date);
//   result.setHours(23, 59, 59, 999);
//   return result;
// }

// function addDays(date: Date, days: number) {
//   const result = new Date(date);
//   result.setDate(result.getDate() + days);
//   return result;
// }

// function formatCurrency(value: unknown) {
//   return `₹${Number(value).toLocaleString("en-IN")}`;
// }

// function formatDate(value: Date) {
//   return value.toLocaleDateString("en-IN");
// }

// async function sendAutomaticReminder(invoice: any, daysBeforeDue: number) {
//   const subject = `Payment Reminder: Invoice ${invoice.invoiceNumber} due in ${daysBeforeDue} days`;

//   const message = `Dear ${invoice.customer.name},

// This is an automatic payment reminder.

// Invoice Number: ${invoice.invoiceNumber}
// Amount Due: ${formatCurrency(invoice.balanceAmount)}
// Due Date: ${formatDate(invoice.dueDate)}

// Your payment is due in ${daysBeforeDue} days.

// Regards,
// ${invoice.user.businessName || invoice.user.name || "Your Business"}`;

//   // HTML template is now generated by the email service

//   const reminder = await prisma.reminder.create({
//     data: {
//       userId: invoice.userId,
//       customerId: invoice.customerId,
//       invoiceId: invoice.id,
//       reminderType: "BEFORE_DUE_DATE",
//       status: "PENDING",
//       subject,
//       message,
//       sentTo: invoice.customer.email,
//     },
//   });

//   try {
//     const emailResponse = await sendPaymentReminderEmail({
//       to: invoice.customer.email,
//       customerName: invoice.customer.name,
//       invoiceNumber: invoice.invoiceNumber,
//       amountDue: formatCurrency(invoice.balanceAmount),
//       dueDate: formatDate(invoice.dueDate),
//       businessName: invoice.user.businessName || invoice.user.name || "Your Business",
//       invoiceStatus: invoice.status,
//       isOverdue: invoice.status === "OVERDUE",
//       daysBeforeDue,
//       reminderMessage: message,
//     });

//     if (!emailResponse.success) {
//       throw new Error("Failed to send automatic reminder email");
//     }

//     await prisma.reminder.update({
//       where: {
//         id: reminder.id,
//       },
//       data: {
//         status: "SENT",
//         resendEmailId: emailResponse.messageId as string,
//         sentAt: new Date(),
//       },
//     });

//     return {
//       invoiceNumber: invoice.invoiceNumber,
//       customer: invoice.customer.email,
//       daysBeforeDue,
//       status: "SENT",
//     };
//   } catch (error) {
//     console.error("AUTO_REMINDER_EMAIL_ERROR", error);

//     await prisma.reminder.update({
//       where: {
//         id: reminder.id,
//       },
//       data: {
//         status: "FAILED",
//       },
//     });

//     return {
//       invoiceNumber: invoice.invoiceNumber,
//       customer: invoice.customer.email,
//       daysBeforeDue,
//       status: "FAILED",
//     };
//   }
// }

// export async function GET(request: Request) {
//   try {
//     const authHeader = request.headers.get("authorization");
//     const cronSecret = process.env.CRON_SECRET;

//     if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
//       return NextResponse.json(
//         { message: "Unauthorized cron request" },
//         { status: 401 }
//       );
//     }

//     const today = startOfDay(new Date());

//     /**
//      * Step 1:
//      * Automatically mark old unpaid invoices as OVERDUE.
//      */
//     const overdueUpdateResult = await prisma.invoice.updateMany({
//       where: {
//         dueDate: {
//           lt: today,
//         },
//         status: {
//           in: ["PENDING", "PARTIALLY_PAID"],
//         },
//       },
//       data: {
//         status: "OVERDUE",
//       },
//     });

//     /**
//      * Step 2:
//      * Send automatic reminders before due date.
//      */
//     const reminderDays = [15, 7, 2];

//     const results = [];

//     for (const daysBeforeDue of reminderDays) {
//       const targetDate = addDays(today, daysBeforeDue);

//       const invoices = await prisma.invoice.findMany({
//         where: {
//           status: {
//             in: ["PENDING", "PARTIALLY_PAID", "OVERDUE"],
//           },
//           dueDate: {
//             gte: startOfDay(targetDate),
//             lte: endOfDay(targetDate),
//           },
//           customer: {
//             email: {
//               not: "",
//             },
//           },
//         },
//         include: {
//           customer: true,
//           user: true,
//           reminders: true,
//         },
//       });

//       for (const invoice of invoices) {
//         /**
//          * Duplicate protection:
//          * Do not send the same 15-day, 7-day, or 2-day reminder twice.
//          */
//         const alreadySent = await prisma.reminder.findFirst({
//           where: {
//             invoiceId: invoice.id,
//             reminderType: "BEFORE_DUE_DATE",
//             status: "SENT",
//             subject: {
//               contains: `due in ${daysBeforeDue} days`,
//             },
//           },
//         });

//         if (alreadySent) {
//           results.push({
//             invoiceNumber: invoice.invoiceNumber,
//             customer: invoice.customer.email,
//             daysBeforeDue,
//             status: "SKIPPED_ALREADY_SENT",
//           });

//           continue;
//         }

//         const result = await sendAutomaticReminder(invoice, daysBeforeDue);
//         results.push(result);
//       }
//     }

//     return NextResponse.json({
//       message: "Automatic reminder and overdue update job completed",
//       overdueInvoicesUpdated: overdueUpdateResult.count,
//       checkedReminderDays: reminderDays,
//       totalActions: results.length,
//       results,
//     });
//   } catch (error) {
//     console.error("CRON_REMINDER_ERROR", error);

//     return NextResponse.json(
//       { message: "Cron reminder failed" },
//       { status: 500 }
//     );
//   }
// }

import { NextResponse } from "next/server";
import { ReminderStatus, ReminderType } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { sendPaymentReminderEmail } from "@/lib/email";
import { decrypt } from "@/lib/encryption";

function startOfDay(date: Date) {
  const result = new Date(date);
  result.setHours(0, 0, 0, 0);
  return result;
}

function endOfDay(date: Date) {
  const result = new Date(date);
  result.setHours(23, 59, 59, 999);
  return result;
}

function addDays(date: Date, days: number) {
  const result = new Date(date);
  result.setDate(result.getDate() + days);
  return result;
}

function subtractMonths(date: Date, months: number) {
  const result = new Date(date);
  result.setMonth(result.getMonth() - months);
  return startOfDay(result);
}

function isSameDay(dateOne: Date, dateTwo: Date) {
  return startOfDay(dateOne).getTime() === startOfDay(dateTwo).getTime();
}

function daysBetween(startDate: Date, endDate: Date) {
  const oneDay = 1000 * 60 * 60 * 24;
  const start = startOfDay(startDate).getTime();
  const end = startOfDay(endDate).getTime();

  return Math.round((end - start) / oneDay);
}

function formatCurrency(value: unknown) {
  return `₹${Number(value).toLocaleString("en-IN")}`;
}

function formatDate(value: Date) {
  return value.toLocaleDateString("en-IN");
}

type ReminderStage = {
  label: string;
  subjectText: string;
  messageText: string;
};

async function sendAutomaticReminder(invoice: any, stage: ReminderStage) {
  const subject = `Payment Reminder: Invoice ${invoice.invoiceNumber} ${stage.subjectText}`;

  const message = `Dear ${invoice.customer.name},

This is an automatic payment reminder.

Invoice Number: ${invoice.invoiceNumber}
Amount Due: ${formatCurrency(invoice.balanceAmount)}
Due Date: ${formatDate(invoice.dueDate)}

${stage.messageText}

Regards,
${invoice.user.businessName || invoice.user.name || "Your Business"}`;

  const reminder = await prisma.reminder.create({
    data: {
      userId: invoice.userId,
      customerId: invoice.customerId,
      invoiceId: invoice.id,
      reminderType: ReminderType.BEFORE_DUE_DATE,
      status: ReminderStatus.PENDING,
      subject,
      message,
      sentTo: invoice.customer.email,
    },
  });

  try {
    const emailResponse = await sendPaymentReminderEmail({
      to: invoice.customer.email,
      customerName: invoice.customer.name,
      invoiceNumber: invoice.invoiceNumber,
      amountDue: formatCurrency(invoice.balanceAmount),
      dueDate: formatDate(invoice.dueDate),
      businessName: invoice.user.businessName || invoice.user.name || "Your Business",
      invoiceStatus: invoice.status,
      isOverdue: invoice.status === "OVERDUE",
      reminderMessage: stage.messageText,
      senderEmail: invoice.user.email,
      senderPass: invoice.user.emailPass ? decrypt(invoice.user.emailPass) : undefined,
    });

    if (!emailResponse.success) {
      throw new Error("Failed to send automatic reminder email");
    }

    await prisma.reminder.update({
      where: {
        id: reminder.id,
      },
      data: {
        status: ReminderStatus.SENT,
        resendEmailId: emailResponse.messageId as string,
        sentAt: new Date(),
      },
    });

    return {
      invoiceNumber: invoice.invoiceNumber,
      customer: invoice.customer.email,
      reminderStage: stage.label,
      status: "SENT",
    };
  } catch (error) {
    console.error("AUTO_REMINDER_EMAIL_ERROR", error);

    await prisma.reminder.update({
      where: {
        id: reminder.id,
      },
      data: {
        status: ReminderStatus.FAILED,
      },
    });

    return {
      invoiceNumber: invoice.invoiceNumber,
      customer: invoice.customer.email,
      reminderStage: stage.label,
      status: "FAILED",
    };
  }
}

function getSixMonthReminderStage(today: Date, dueDate: Date) {
  const daysLeft = daysBetween(today, dueDate);

  if (daysLeft <= 30) {
    return null;
  }

  for (let monthsBeforeDue = 6; monthsBeforeDue <= 120; monthsBeforeDue += 6) {
    const reminderDate = subtractMonths(dueDate, monthsBeforeDue);

    if (isSameDay(today, reminderDate)) {
      return {
        label: `${monthsBeforeDue} months before due date`,
        subjectText: `due in ${monthsBeforeDue} months`,
        messageText: `Your payment is due in ${monthsBeforeDue} months. Kindly plan the payment before the due date.`,
      };
    }
  }

  return null;
}

function getDayBasedReminderStage(daysBeforeDue: number) {
  return {
    label: `${daysBeforeDue} days before due date`,
    subjectText: `due in ${daysBeforeDue} days`,
    messageText: `Your payment is due in ${daysBeforeDue} days. Kindly complete the payment on or before the due date.`,
  };
}

export async function GET(request: Request) {
  try {
    const authHeader = request.headers.get("authorization");
    const cronSecret = process.env.CRON_SECRET;

    if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
      return NextResponse.json(
        { message: "Unauthorized cron request" },
        { status: 401 }
      );
    }

    const today = startOfDay(new Date());

    /**
     * Step 1:
     * Automatically mark old unpaid invoices as OVERDUE.
     */
    const overdueUpdateResult = await prisma.invoice.updateMany({
      where: {
        dueDate: {
          lt: today,
        },
        status: {
          in: ["PENDING", "PARTIALLY_PAID"],
        },
      },
      data: {
        status: "OVERDUE",
      },
    });

    const totalOverdueInvoices = await prisma.invoice.count({
      where: {
        status: "OVERDUE",
      },
    });

    const results = [];

    /**
     * Step 2:
     * Long-term reminders.
     * Sends every 6 months before due date, while more than 1 month is left.
     *
     * Example:
     * 24 months before
     * 18 months before
     * 12 months before
     * 6 months before
     */
    const futureInvoices = await prisma.invoice.findMany({
      where: {
        status: {
          in: ["PENDING", "PARTIALLY_PAID"],
        },
        dueDate: {
          gt: addDays(today, 30),
        },
        customer: {
          email: {
            not: "",
          },
        },
      },
      include: {
        customer: true,
        user: true,
        reminders: true,
      },
    });

    for (const invoice of futureInvoices) {
      const stage = getSixMonthReminderStage(today, invoice.dueDate);

      if (!stage) {
        continue;
      }

      const alreadySent = await prisma.reminder.findFirst({
        where: {
          invoiceId: invoice.id,
          reminderType: ReminderType.BEFORE_DUE_DATE,
          status: ReminderStatus.SENT,
          subject: {
            contains: stage.subjectText,
          },
        },
      });

      if (alreadySent) {
        results.push({
          invoiceNumber: invoice.invoiceNumber,
          customer: invoice.customer.email,
          reminderStage: stage.label,
          status: "SKIPPED_ALREADY_SENT",
        });

        continue;
      }

      const result = await sendAutomaticReminder(invoice, stage);
      results.push(result);
    }

    /**
     * Step 3:
     * Final short-term reminders.
     * Sends 15 days and 2 days before due date.
     */
    const dayReminderStages = [15, 2];

    for (const daysBeforeDue of dayReminderStages) {
      const targetDate = addDays(today, daysBeforeDue);

      const invoices = await prisma.invoice.findMany({
        where: {
          status: {
            in: ["PENDING", "PARTIALLY_PAID"],
          },
          dueDate: {
            gte: startOfDay(targetDate),
            lte: endOfDay(targetDate),
          },
          customer: {
            email: {
              not: "",
            },
          },
        },
        include: {
          customer: true,
          user: true,
          reminders: true,
        },
      });

      for (const invoice of invoices) {
        const stage = getDayBasedReminderStage(daysBeforeDue);

        const alreadySent = await prisma.reminder.findFirst({
          where: {
            invoiceId: invoice.id,
            reminderType: ReminderType.BEFORE_DUE_DATE,
            status: ReminderStatus.SENT,
            subject: {
              contains: stage.subjectText,
            },
          },
        });

        if (alreadySent) {
          results.push({
            invoiceNumber: invoice.invoiceNumber,
            customer: invoice.customer.email,
            reminderStage: stage.label,
            status: "SKIPPED_ALREADY_SENT",
          });

          continue;
        }

        const result = await sendAutomaticReminder(invoice, stage);
        results.push(result);
      }
    }

    return NextResponse.json({
      message: "Automatic reminder and overdue update job completed",
      overdueInvoicesUpdated: overdueUpdateResult.count,
      totalOverdueInvoices,
      longTermReminderRule:
        "Every 6 months before due date while more than 1 month is left",
      finalReminderDays: dayReminderStages,
      totalActions: results.length,
      results,
    });
  } catch (error) {
    console.error("CRON_REMINDER_ERROR", error);

    return NextResponse.json(
      { message: "Cron reminder failed" },
      { status: 500 }
    );
  }
}